# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in twsearch.gemspec
gemspec

gem "debug"
gem "gem-release"
gem "rake", "~> 13.3"
gem "rake-compiler", "~> 1.3"
gem "rspec", "~> 3.13"
gem "rubocop", "~> 1.81"
gem "rubocop-rake", "~> 0.7"
gem "rubocop-rspec", "~> 3.7"
