# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rb_sys/extensiontask"

desc "Build extension"
task build: :compile

GEMSPEC = Gem::Specification.load("twips.gemspec")

RbSys::ExtensionTask.new("twips-rb", GEMSPEC) do |ext|
  ext.lib_dir = "lib/twips"
end

task default: %i[compile spec rubocop]
