fn main() {
    cxx_build::bridge("src/rs/main.rs")
        .file("src/cpp/antipode.cpp")
        .file("src/cpp/calcsymm.cpp")
        .file("src/cpp/canon.cpp")
        .file("src/cpp/cmdlineops.cpp")
        .file("src/cpp/filtermoves.cpp")
        .file("src/cpp/findalgo.cpp")
        .file("src/cpp/generatingset.cpp")
        .file("src/cpp/god.cpp")
        .file("src/cpp/index.cpp")
        .file("src/cpp/parsemoves.cpp")
        .file("src/cpp/prunetable.cpp")
        .file("src/cpp/puzdef.cpp")
        .file("src/cpp/readksolve.cpp")
        .file("src/cpp/ffi/ffi_api.cpp")
        .file("src/cpp/ffi/rust_api.cpp")
        .file("src/cpp/solve.cpp")
        .file("src/cpp/test.cpp")
        .file("src/cpp/threads.cpp")
        .file("src/cpp/twsearch.cpp")
        .file("src/cpp/util.cpp")
        .file("src/cpp/workchunks.cpp")
        .file("src/cpp/rotations.cpp")
        .file("src/cpp/orderedgs.cpp")
        .file("src/cpp/cityhash/src/city.cc")
        .file("src/cpp/coset.cpp")
        .file("src/cpp/descsets.cpp")
        .file("src/cpp/ordertree.cpp")
        .file("src/cpp/unrotate.cpp")
        .file("src/cpp/shorten.cpp")
        .flag("-std=c++17")
        .flag("-DASLIBRARY")
        .flag("-DTWSEARCH_VERSION=v0.4.2-7-g4a9107fa")
        // .flag("-lpthread") # Unneeded?
        .flag("-DUSE_PTHREADS")
        .flag("-DHAVE_FFSLL")
        .compile("twsearch-rs");

    println!("cargo:rerun-if-changed=src/cpp/antipode.cpp");
    println!("cargo:rerun-if-changed=src/cpp/calcsymm.cpp");
    println!("cargo:rerun-if-changed=src/cpp/canon.cpp");
    println!("cargo:rerun-if-changed=src/cpp/cmdlineops.cpp");
    println!("cargo:rerun-if-changed=src/cpp/filtermoves.cpp");
    println!("cargo:rerun-if-changed=src/cpp/findalgo.cpp");
    println!("cargo:rerun-if-changed=src/cpp/generatingset.cpp");
    println!("cargo:rerun-if-changed=src/cpp/god.cpp");
    println!("cargo:rerun-if-changed=src/cpp/index.cpp");
    println!("cargo:rerun-if-changed=src/cpp/parsemoves.cpp");
    println!("cargo:rerun-if-changed=src/cpp/prunetable.cpp");
    println!("cargo:rerun-if-changed=src/cpp/puzdef.cpp");
    println!("cargo:rerun-if-changed=src/cpp/readksolve.cpp");
    println!("cargo:rerun-if-changed=src/cpp/ffi/ffi_api.cpp");
    println!("cargo:rerun-if-changed=src/cpp/ffi/rust_api.cpp");
    println!("cargo:rerun-if-changed=src/cpp/solve.cpp");
    println!("cargo:rerun-if-changed=src/cpp/test.cpp");
    println!("cargo:rerun-if-changed=src/cpp/threads.cpp");
    println!("cargo:rerun-if-changed=src/cpp/twsearch.cpp");
    println!("cargo:rerun-if-changed=src/cpp/util.cpp");
    println!("cargo:rerun-if-changed=src/cpp/workchunks.cpp");
    println!("cargo:rerun-if-changed=src/cpp/rotations.cpp");
    println!("cargo:rerun-if-changed=src/cpp/orderedgs.cpp");
    println!("cargo:rerun-if-changed=src/cpp/cityhash/src/city.cc");
    println!("cargo:rerun-if-changed=src/cpp/coset.cpp");
    println!("cargo:rerun-if-changed=src/cpp/descsets.cpp");
    println!("cargo:rerun-if-changed=src/cpp/ordertree.cpp");
    println!("cargo:rerun-if-changed=src/cpp/unrotate.cpp");
    println!("cargo:rerun-if-changed=src/cpp/shorten.cpp");
}
