fn main() {
    cxx_build::bridge("./rs/main.rs")
        .file("antipode.cpp")
        .file("calcsymm.cpp")
        .file("canon.cpp")
        .file("cmdlineops.cpp")
        .file("filtermoves.cpp")
        .file("generatingset.cpp")
        .file("god.cpp")
        .file("index.cpp")
        .file("parsemoves.cpp")
        .file("prunetable.cpp")
        .file("puzdef.cpp")
        .file("readksolve.cpp")
        .file("ffi/ffi_api.cpp")
        .file("ffi/rust_api.cpp")
        .file("solve.cpp")
        .file("test.cpp")
        .file("threads.cpp")
        .file("twsearch.cpp")
        .file("util.cpp")
        .file("workchunks.cpp")
        .file("rotations.cpp")
        .file("cityhash/src/city.cc")
        .file("unrotate.cpp")
        .file("shorten.cpp")
        .file("cmds.cpp")
        .flag("-std=c++17")
        .flag("-DASLIBRARY")
        .flag("-DTWSEARCH_VERSION=v0.4.2-7-g4a9107fa")
        // .flag("-lpthread") # Unneeded?
        .flag("-DUSE_PTHREADS")
        .compile("twsearch-cpp-wrapper");

    println!("cargo:rerun-if-changed=antipode.cpp");
    println!("cargo:rerun-if-changed=calcsymm.cpp");
    println!("cargo:rerun-if-changed=canon.cpp");
    println!("cargo:rerun-if-changed=cmdlineops.cpp");
    println!("cargo:rerun-if-changed=filtermoves.cpp");
    println!("cargo:rerun-if-changed=findalgo.cpp");
    println!("cargo:rerun-if-changed=generatingset.cpp");
    println!("cargo:rerun-if-changed=god.cpp");
    println!("cargo:rerun-if-changed=index.cpp");
    println!("cargo:rerun-if-changed=parsemoves.cpp");
    println!("cargo:rerun-if-changed=prunetable.cpp");
    println!("cargo:rerun-if-changed=puzdef.cpp");
    println!("cargo:rerun-if-changed=readksolve.cpp");
    println!("cargo:rerun-if-changed=ffi/ffi_api.cpp");
    println!("cargo:rerun-if-changed=ffi/rust_api.cpp");
    println!("cargo:rerun-if-changed=solve.cpp");
    println!("cargo:rerun-if-changed=test.cpp");
    println!("cargo:rerun-if-changed=threads.cpp");
    println!("cargo:rerun-if-changed=twsearch.cpp");
    println!("cargo:rerun-if-changed=util.cpp");
    println!("cargo:rerun-if-changed=workchunks.cpp");
    println!("cargo:rerun-if-changed=rotations.cpp");
    println!("cargo:rerun-if-changed=orderedgs.cpp");
    println!("cargo:rerun-if-changed=cityhash/src/city.cc");
    println!("cargo:rerun-if-changed=coset.cpp");
    println!("cargo:rerun-if-changed=descsets.cpp");
    println!("cargo:rerun-if-changed=ordertree.cpp");
    println!("cargo:rerun-if-changed=unrotate.cpp");
    println!("cargo:rerun-if-changed=shorten.cpp");
    println!("cargo:rerun-if-changed=cmds.cpp");
}
