[profile.release]
strip = false # TODO: why does `true` and `"symbols"` not work? (Also, this setting might not even affect the WASM output?)
opt-level = "z"
lto = true

[build]
rustflags = ["-C", "target-feature=+bulk-memory"]
