#!/usr/bin/env bash

set -euo pipefail

# From https://emscripten.org/docs/getting_started/downloads.html

git clone https://github.com/emscripten-core/emsdk.git
cd emsdk

# Fetch the latest version of the emsdk (not needed the first time you clone)
# git pull
# Download and install the latest SDK tools.
./emsdk install latest
# Make the "latest" SDK "active" for the current user. (writes .emscripten file)
./emsdk activate latest
# Activate PATH and other environment variables in the current terminal
# source ./emsdk_env.sh



# Next steps:
# - To conveniently access emsdk tools from the command line,
#   consider adding the following directories to your PATH:
#     /workspaces/twsearch/emsdk
#     /workspaces/twsearch/emsdk/node/14.18.2_64bit/bin
#     /workspaces/twsearch/emsdk/upstream/emscripten
# - This can be done for the current shell by running:
#     source "/workspaces/twsearch/emsdk/emsdk_env.sh"
# - Configure emsdk in your shell startup scripts by running:
#     echo 'source "/workspaces/twsearch/emsdk/emsdk_env.sh"' >> $HOME/.bash_profile
