module Twips
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides

  def self.random_scramble_for_event: (String) -> String
  def self.derive_scramble_for_event: (String, String, String) -> String
end
